# Generated by Django 5.2.12 on 2026-04-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('cargo', models.CharField(choices=[('mecanico', 'Mecánico'), ('cajero', 'Cajero'), ('mesero', 'Mesero'), ('cocinero', 'Cocinero'), ('administrador', 'Administrador'), ('otro', 'Otro')], max_length=20)),
                ('area', models.CharField(choices=[('taller', 'Taller'), ('restaurante', 'Restaurante'), ('ambos', 'Ambos')], max_length=20)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_ingreso', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'empleados',
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
