# Generated by Django 5.2.12 on 2026-04-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=200)),
                ('cliente_email', models.EmailField(max_length=254)),
                ('cliente_telefono', models.CharField(max_length=20)),
                ('vehiculo_placa', models.CharField(max_length=20)),
                ('vehiculo_marca', models.CharField(max_length=100)),
                ('vehiculo_modelo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('fecha_reserva', models.DateTimeField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
